name: Build Lib

on:
  push:
    branches: [ master ]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace}}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  create-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.step1.outputs.version }}
    steps:
      - id: step1
        shell: bash
        run: echo  "version=$(date '+%Y.%m.%d.%H%M')" >> "$GITHUB_OUTPUT"
      - name: show version
        shell: bash
        run: echo ${{steps.step1.outputs.version}}

  OpenHardwareMonitorLib:
    name: OpenHardwareMonitorLib
    runs-on: ubuntu-latest
    needs: create-version
    steps:
      - uses: actions/checkout@v3

      # Install the .NET SDK indicated in the global.json file
      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      # Create the NuGet package in the folder from the environment variable NuGetDirectory
      - run: dotnet pack OpenHardwareMonitor.csproj --configuration Release --output ${{ env.NuGetDirectory }} /p:Version=${{needs.create-version.outputs.version}}

      # Publish all NuGet packages to NuGet.org
      # Use --skip-duplicate to prevent errors if a package with the same version already exists.
      # If you retry a failed workflow, already published packages will be skipped without error.
      - name: Publish NuGet package
        run: |
          foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }



